version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

        #- run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build-storybook

      - run: 
          name: "Commiting docs files and publishing module"
          command: |
            if [[ $CIRCLE_BRANCH == 'master' ]]; then
              echo "We're on master branch, deploying..."
              BRANCH=$CIRCLE_BRANCH ./deploy.sh;
            else
              echo "Not on master branch, skipping deployment."
            fi;
          
