version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn run build-storybook
      - run: git add docs
      - run: git commit -m 'Updating github pages [ci skip]'

      - run: yarn run unleash -p
        
        #- run: if [ $TRAVIS_BRANCH == 'circleci' ]; then yarn run unleash -p; fi

