version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - run: 
          name: "Git user configuration"
          command: |
            git config --global user.email "mist@ethereum.org" && 
            git config --global user.name "Mist-bot"

      -run:
        name: "npm configuration"
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc


      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       

      - run: yarn run build-storybook
      

      - run: 
          name: "Commiting docs files, if changed"
          command: |
            if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
              git add docs;
              git commit -am 'Updating github pages [ci skip]';
              git push origin $CIRCLE_BRANCH;
            fi

      - run: npm version patch
      - run: npm publish
      - run: git push --follow-tags
        
