version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
       

      - add_ssh_keys:
          fingerprints: 
            - "f6:dc:2a:6c:7b:0e:f6:72:b9:b9:de:82:a0:43:20:da"

      - run: yarn run build-storybook
      
      - run: git config --global user.email "mist@ethereum.org"
      - run: git config --global user.name "Mist-bot"
      - run: git add docs
      - run: git commit -m 'Updating github pages [ci skip]'
      - run: git push origin $CIRCLE_BRANCH

      - run: yarn run unleash -d -p
        
        #- run: if [ $CIRCLE_BRANCH == 'circleci' ]; then yarn run unleash -p; fi

